name: gcet_tracker
description: "MyGCET - Student portal for attendance, materials, results and more"
publish_to: "none"

version: 3.0.0+3

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  fl_chart: ^1.1.1
  url_launcher: ^6.2.4
  html: ^0.15.4
  dio: ^5.9.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.3.0
  crypto: ^3.0.7
  file_picker: ^10.3.8
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  csv: ^6.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  uuid: ^4.5.2
  flutter_slidable: ^4.0.3
  lottie: ^3.3.2
  liquid_pull_to_refresh: ^3.0.1
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/My GCET_20251225_134706_0000.png"
  adaptive_icon_background: "#1565C0"
  adaptive_icon_foreground: "assets/images/My GCET_20251225_134706_0000.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/cloud.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
